import csv

def generate_tb_csv():
    # Generate CSV for ThingsBoard Bulk Provisioning
    # Columns required conventionally: Name, Type, Label, Description
    
    with open('thingsboard_devices.csv', 'w', newline='') as csvfile:
        fieldnames = ['Name', 'Type', 'Label', 'Description']
        writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
        writer.writeheader()
        
        for f in range(1, 11):
            for r in range(1, 21):
                node_id = f"b01-f{f:02d}-r{r:03d}"
                node_type = "MQTT-ThermalSensor" if r <= 10 else "CoAP-ThermalSensor"
                
                writer.writerow({
                    'Name': node_id,
                    'Type': node_type,
                    'Label': f"Room {r} on Floor {f}",
                    'Description': f"Autogenerated {node_type} node"
                })
    print("Generated thingsboard_devices.csv for Bulk Import.")

if __name__ == "__main__":
    generate_tb_csv()
